language: node_js

node_js:
  - stable
  - '8'
  - '6'

sudo: false

env:
  global:
    secure: d1huaNT8SRJYw1m08WwZlxk8EuAPiLDzqDmxxb2HsriF3uy5bnIhP/570oUAGaphMfhX1XA9poF082klBGQr/WWBDf14xI0TFgu6k4WR0uuIokROVbTVeJAnPjz3Q/RgVB+rZP2LCtu/ttHMN64awrfVUAesBrfYCkt4MEKeR69e6JUK3p1Ls4bQt1qhdeBB3K1D5xoZ00taSSgbjIVG65BfbJpQ+utjq1WjiK+TkjqTwTrqG7BTUPF7y7eETO6Xoo0w8VE7d5CKmP9J+39LNDWT53piQFg+azh1o9pg72iBXhPr2UWUb3GcvHSJo5DWkiJWBWE52KksNkWRf5JPDffnKhnJLZfAjNuD9b/LUPiXr10sANryBOyHh19B1ts4FtIANek/sb7JDem5oYqLzcq7W+kTLjJs6BNiAC7dCpidsBSf0KoNhFQPjsMJEyEkxKF/WLsBM6EaK4plmQ/1yYTJOHp3XzUvlpw8vhn0FGduYbCl5FRBmVy12RAhRv1MmW12iy08qeFlZyL0z55HWcoe+cFhAaehXGb+np4AwJRXS4Q0rU6NU0Vl8mz2GIkjgAAWUltufXIWlWxo9RyrO8SPK9rTYigdJOoqwjkucuGuRhLkdQwQBUmI3ERChBwhdeM2Fw1DlpdbQGUHJmV+H3l+9UWz0QG3vRLxB7lEHqs=

before_install:
  - npm install -g pr-bumper@^3.0.0

install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

deploy:
  provider: npm
  email: dogmaiobot@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8'
    tags: true
  api_key:
    secure: d2Kx2XJlCK4KqgYuHczqYPenUGsZGGcRzjAw6exHeqpi0eNi6IhvXRhk7b0Q6Encp115IiL0RMi+WKldaUK4qp14WoNWt7HK/F7LS1siMrkZL7KvG5HmpyLh32qoxZqhnSuZ0UJE2dnNmnll5Q7HZS3MG3jFLPBgvBSwf/P6Bvly4KiO3tZGzkKdJsobq3EASouHxuHsVsjQZgENiJ3DXAoC0AyEYL5cA44Tuge/aybOz5Qumwzz0CPQUt+FAjrBifkfenIHml/fFS73FJjmlmEY0pYgvrys05AXyBa5MtMgo1+ir5naSdaP3d+evy+RgLmpAaTfUyzrGHISmU+sDTb+rTftL+DVjIRL4jmCQvsfh5gPMpryf5zgmP6zmzMDZugf7ilaQDAEEXqExF1R+Ct+wscI4L/M+kkmRX7n+6ZkX5ubR4w2f0HbEiyIbiCVWSDIs4a2b0vpxpYT0Jr19hJxzwKmjHpnVuqGi/WPsSS923y37R1/wiqN1PT4jFLbIofXVmq0ppItxM+AQiAnz6W/s1S6h9qw7Rnj+mwWV13iF2HL9r09Td/87t1O8tjli6vXJYeALE8usxLn0bqISRhmaAvDJ+aJ6JjXY+EwMXulkgaK2Uhf4EH1WZjvjuDYKNRasacLlf7Jj33S/4/fBgM6SLgWOwDC2k14izmgG1A=
